# Path to the zsh directory
export ZSH="${HOME}/.zsh"

# Configure history
export HISTFILE="${HOME}/.zsh/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS

# Some useful variables
THEMES_DIR="${ZSH}/themes"
PLUGINS_DIR="${ZSH}/plugins"

# source alias file if it exists
if [[ -f ~/.zshaliases ]]; then
  source ~/.zshaliases;
fi

# Pyenv configuration
if [[ -d "${HOME}/.pyenv" ]]; then eval "$(pyenv init --path)"; fi

if [[ -d "${HOME}/.pyenv/plugins/pyenv-virtualenv" ]]; then
  TMP_PATH=$PATH
  eval "$(pyenv virtualenv-init -)";
  export PATH=$TMP_PATH
  unset TMP_PATH
fi

# Initialise and configure prompt system
fpath+=("$THEMES_DIR/mu/")
autoload -Uz compinit; compinit
autoload -Uz promptinit; promptinit
prompt mu
source "${PLUGINS_DIR}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# Source custom plugins if they exist
[[ -f "${PLUGINS_DIR}/jdfs/jdfs.zsh" ]] && source "${PLUGINS_DIR}/jdfs/jdfs.zsh"
[[ -f "${PLUGINS_DIR}/nnn/nnn.zsh" ]] && source "${PLUGINS_DIR}/nnn/nnn.zsh"

bindkey -M vicmd 'k' history-beginning-search-backward
bindkey -M vicmd 'j' history-beginning-search-forward

export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=false
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND=false

# Source override hook
[[ -f ~/.zoverride ]] && source ~/.zoverride
