#!/bin/sh

echo "${VISUAL}" "$@" >> /tmp/kedit.log

kitten @ launch \
    --password 'kedit' \
    --copy-env \
    --type window \
    --title kedit \
    --no-response \
    --cwd current \
    "${VISUAL}" "$@"
