" enable line numbers and syntax highlighting
set number
syntax on

" show list chars
set list

" break at words
set linebreak

" configure spaces for intentation
set tabstop=8 softtabstop=0
set shiftwidth=4
set smarttab
set expandtab

" enable cursorline
set cursorline

" set 256 color mode
set t_Co=256

" whitespace highlighting
set listchars=trail:·,tab:→\ ,lead:·,nbsp:◦
highlight SpecialKey ctermfg=241 ctermbg=NONE guifg=#5c6370 guibg=NONE
highlight Trail ctermfg=NONE ctermbg=168 guifg=NONE guibg=#e06c75
autocmd InsertEnter * match Trail //
autocmd VimEnter,WinEnter,InsertLeave * match Trail /\s\+$/

" "TODO" highlighting
highlight Todo cterm=underline ctermfg=73 ctermbg=NONE gui=underline guifg=#56b6c2 guibg=NONE
autocmd VimEnter,WinEnter * match Todo /TODO/

" set textwidth to 72 for git commit
autocmd FileType gitcommit set textwidth=72
