" Enable line numbers and syntax highlighting.
set number
syntax enable
filetype on
filetype plugin on

" Show and configure listchars.
set list
set listchars=trail:·,tab:→\ ,lead:·,nbsp:◦

" Configure spaces for intentation.
set tabstop=8 softtabstop=0
set shiftwidth=4
set smarttab
set expandtab

" Break at words.
set linebreak

" Enable cursorline.
set cursorline
colorscheme onehalfdark

" whitespace highlighting
highlight SpecialKey ctermfg=241 ctermbg=NONE guifg=#5c6370 guibg=NONE
highlight Trail ctermfg=NONE ctermbg=168 guifg=NONE guibg=#e06c75
autocmd InsertEnter * match Trail //
autocmd VimEnter,WinEnter,InsertLeave * match Trail /\s\+$/

" "TODO" highlighting
highlight Todo cterm=underline ctermfg=73 ctermbg=NONE gui=underline guifg=#56b6c2 guibg=NONE
syntax match Todo /TODO/

" configure status line
set laststatus=2
set statusline=%<%5*\ %f\ %h%w%m%r%*%=%a\ %7*\ B\ %n\ ::\ %Y\ @\ %(%l:%c%)\ %P\ %*
