[general]
use-terminal-pinentry=true

[ui]
sidebar-width=32
dirlist-tree=true

[compose]
editor=nvim

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
.headers=colorize
