[general]
default-save-path = ~/Downloads/
use-terminal-pinentry=true

[ui]
sidebar-width=32
dirlist-tree=true

[compose]
editor=nvim

[filters]
text/plain=wrap -w 72 | colorize
text/calendar=calendar
text/html=custom-html
text/*=cbat
message/delivery-status=colorize
message/rfc822=colorize
.headers=colorize
